name: supermarket_deliveryagent_fe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  

flutter:
  uses-material-design: true

  assets:
    - assets/appicons.png
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicons.png"
  adaptive_icon_background: "#27AE60"
  adaptive_icon_foreground: "assets/appicons.png"
  remove_alpha_ios: true

